### PR TITLE
Feature/recursion

### PR DESCRIPTION
**Pull request by robbruce**
Added the ability to read files recursively with additional option passed into configuration

### CODE REVIEW

**Comment by makubi** [comment]
Thanks for your contribution!

Could you add a short summary to the "Override variables" section in https://github.com/makubi/avrohugger-maven-plugin#override-variables?

I think you can also remove the `def generateScalaFiles(inputDirectory: File, outputDirectory: String, log: Log): Unit` method as it's only used in the unit test and call `generateScalaFiles(inputDirectory, outputDirectory, log, false)` instead.

**Comment by robbruce** [comment]
All done, ready for merge and version bumping

**Comment by makubi** [comment]
Nice! I am gonna release a new version in the next few days.

**Comment by makubi** [comment]
@robbruce I've released a new artifact. Version 1.1 includes your changes.

**Pull request merged**
